# Build Neural Network in Tensorflow

In [ ]:
# data --> 
# array([[0.1, 0.2], [0.1, 0.2]])
# array([[0.3], [0.4]])

# build model
# complile model
# train model
# evaluate model

In [8]:
# libraries
import numpy as np
from random import random
from sklearn.model_selection import train_test_split

import tensorflow as tf

In [10]:
# define function to generate toy data
def generate_data(num_samples, test_size):
    x = np.array([[random()/2 for _ in range(2)] for _ in range(num_samples)])
    y = np.array([[i[0] + i[1]] for i in x])
    x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3)
    
    return x_train, x_test, y_train, y_test

x_train, x_test, y_train, y_test = generate_data(5000, 0.3)
print(x_train.shape, x_test.shape, y_train.shape, y_test.shape)

In [80]:
# build model: 2 -> 5 -> 1
model = tf.keras.Sequential(
    [tf.keras.layers.Dense(units = 5, input_dim=2, activation="sigmoid"),
    tf.keras.layers.Dense(units = 1, activation="sigmoid")]
)

# complile model
optimizer = tf.keras.optimizers.SGD(learning_rate=0.1)
model.compile(optimizer = optimizer, loss = "MSE")

In [81]:
# train model
model.fit(x_train, y_train, epochs=100)

Epoch 1/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0496
Epoch 2/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0441
Epoch 3/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0436
Epoch 4/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0432
Epoch 5/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0428
Epoch 6/100
110/110 [==============================] - 0s 2ms/step - loss: 0.0423
Epoch 7/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0419
Epoch 8/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0415
Epoch 9/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0411
Epoch 10/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0406
Epoch 11/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0402
Epoch 12/100
110/110 [==============================] - 0s 1ms/step - loss: 0.0397
Epoch 13/100


110/110 [==============================] - 0s 1ms/step - loss: 7.0173e-04
Epoch 99/100
110/110 [==============================] - 0s 1ms/step - loss: 6.7587e-04
Epoch 100/100
110/110 [==============================] - 0s 2ms/step - loss: 6.5195e-04


In [82]:
# evaluate model
print("Model evaluation using test set")
model.evaluate(x=x_test, y=y_test)

Model evaluation using test set
47/47 [==============================] - 0s 1ms/step - loss: 5.7591e-04


0.0005759109044447541

In [83]:
# make predictions
data = np.array([[0.1, 0.4],[0.5, 0.3]])

predictions = model.predict(data)

predictions

array([[0.4991965 ],
       [0.76897514]], dtype=float32)

In [ ]:
#END